export const ALL_CLASSES = [
    'Monk',
    'Monk: Way of Mercy',
    'Monk: Way of the Astral Self',
    'Monk: Way of the Drunken Master',
    'Monk: Way of the Four Elements',
    'Monk: Way of the Kensei',
    'Monk: Way of the Long Death',
    'Monk: Way of the Open Hand',
    'Monk: Way of the Shadow',
    'Monk: Way of the Sun Soul',
    'Monk: Way of the Ascendant Dragon',
    'Paladin',
    'Paladin: Oath of Devotion',
    'Paladin: Oath of Glory',
    'Paladin: Oath of Redemption',
    'Paladin: Oath of Conquest',
    'Paladin: Oath of the Ancients',
    'Paladin: Oath of the Crown',
    'Paladin: Oath of the Watchers',
    'Paladin: Oathbreaker',
    'Paladin: Oath of Vengeance',
    'Ranger',
    'Ranger: Beast Master',
    'Ranger: Fey Wanderer',
    'Ranger: Gloom Stalker',
    'Ranger: Horizon Walker',
    'Ranger: Hunter',
    'Ranger: Monster Slayer',
    'Ranger: Swarmkeeper',
    'Ranger: Drakewarden',
    'Rogue',
    'Rogue: Arcane Trickster',
    'Rogue: Assassin',
    'Rogue: Inquisitive',
    'Rogue: Mastermind',
    'Rogue: Phantom',
    'Rogue: Scout',
    'Rogue: Soulknife',
    'Rogue: Swashbuckler',
    'Rogue: Thief',
    'Sorcerer',
    'Sorcerer: Aberrant Mind',
    'Sorcerer: Clockwork Soul',
    'Sorcerer: Divine Soul',
    'Sorcerer: Draconic Bloodline',
    'Sorcerer: Shadow Magic',
    'Sorcerer: Storm Sorcery',
    'Sorcerer: Wild Magic',
    'Warlock',
    'Warlock: The Archfey',
    'Warlock: The Celestial',
    'Warlock: The Fathomless',
    'Warlock: The Fiend',
    'Warlock: The Genie',
    'Warlock: The Great Old One',
    'Warlock: The Hexblade',
    'Warlock: The Undying',
    'Warlock: The Undead',
    'Wizard',
    'Wizard: School of Abjuration',
    'Wizard: School of Conjuration',
    'Wizard: School of Divination',
    'Wizard: School of Enchantment',
    'Wizard: School of Evocation',
    'Wizard: School of Illusion',
    'Wizard: School of Necromancy',
    'Wizard: School of Transmutation',
    'Wizard: Bladesinging',
    'Wizard: Chronurgy Magic',
    'Wizard: Graviturgy Magic',
    'Wizard: Order of Scribes',
    'Wizard: War Magic'
] as const;

export type Classes = typeof ALL_CLASSES[number];