export const ALL_CLASS_TYPES = [
    'Artificer',
    'Artificer: Alchemist',
    'Artificer: Armorer',
    'Artificer: Artillerist',
    'Artificer: Battle Smith',
    'Barbarian',
    'Barbarian: Path of the Ancestral Guardian',
    'Barbarian: Path of the Beast',
    'Barbarian: Path of the Berserker',
    'Barbarian: Path of the Giant',
    'Barbarian: Path of the Storm Herald',
    'Barbarian: Path of the Totem Warrior',
    'Barbarian: Path of Wild Magic',
    'Barbarian: Path of the Zealot',
    'Bard',
    'Bard: College of Creation',
    'Bard: College of Eloquence',
    'Bard: College of Glamour',
    'Bard: College of Lore',
    'Bard: College of Spirits',
    'Bard: College of Swords',
    'Bard: College of Valor',
    'Bard: College of Whispers',
    'Blood Hunter',
    'Blood Hunter: Order of the Ghostslayer',
    'Blood Hunter: Order of the Lycan',
    'Blood Hunter: Order of the Mutant',
    'Blood Hunter: Order of the Profane Soul',
    'Cleric',
    'Cleric: Arcana Domain',
    'Cleric: Death Domain',
    'Cleric: Forge Domain',
    'Cleric: Grave Domain',
    'Cleric: Knowledge Domain',
    'Cleric: Life Domain',
    'Cleric: Light Domain',
    'Cleric: Nature Domain',
    'Cleric: Order Domain',
    'Cleric: Peace Domain',
    'Cleric: Tempest Domain',
    'Cleric: Trickery Domain',
    'Cleric: Twilight Domain',
    'Cleric: War Domain',
    'Druid',
    'Druid: Circle of Dreams',
    'Druid: Circle of the Land',
    'Druid: Circle of the Moon',
    'Druid: Circle of the Shepherd',
    'Druid: Circle of Spores',
    'Druid: Circle of Stars',
    'Druid: Circle of Wildfire',
    'Fighter',
    'Fighter: Arcane Archer',
    'Fighter: Battle Master',
    'Fighter: Cavalier',
    'Fighter: Champion',
    'Fighter: Echo Knight',
    'Fighter: Eldritch Knight',
    'Fighter: Psi Warrior',
    'Fighter: Rune Knight',
    'Fighter: Samurai',
    'Monk',
    'Monk: Way of Mercy',
    'Monk: Way of the Astral Self',
    'Monk: Way of the Drunken Master',
    'Monk: Way of the Four Elements',
    'Monk: Way of the Kensei',
    'Monk: Way of the Long Death',
    'Monk: Way of the Open Hand',
    'Monk: Way of the Shadow',
    'Monk: Way of the Sun Soul',
    'Monk: Way of the Ascendant Dragon',
    'Paladin',
    'Paladin: Oath of Devotion',
    'Paladin: Oath of Glory',
    'Paladin: Oath of Redemption',
    'Paladin: Oath of Conquest',
    'Paladin: Oath of the Ancients',
    'Paladin: Oath of the Crown',
    'Paladin: Oath of the Watchers',
    'Paladin: Oathbreaker',
    'Paladin: Oath of Vengeance',
    'Ranger',
    'Ranger: Beast Master',
    'Ranger: Fey Wanderer',
    'Ranger: Gloom Stalker',
    'Ranger: Horizon Walker',
    'Ranger: Hunter',
    'Ranger: Monster Slayer',
    'Ranger: Swarmkeeper',
    'Ranger: Drakewarden',
    'Rogue',
    'Rogue: Arcane Trickster',
    'Rogue: Assassin',
    'Rogue: Inquisitive',
    'Rogue: Mastermind',
    'Rogue: Phantom',
    'Rogue: Scout',
    'Rogue: Soulknife',
    'Rogue: Swashbuckler',
    'Rogue: Thief',
    'Sorcerer',
    'Sorcerer: Aberrant Mind',
    'Sorcerer: Clockwork Soul',
    'Sorcerer: Divine Soul',
    'Sorcerer: Draconic Bloodline',
    'Sorcerer: Shadow Magic',
    'Sorcerer: Storm Sorcery',
    'Sorcerer: Wild Magic',
    'Warlock',
    'Warlock: The Archfey',
    'Warlock: The Celestial',
    'Warlock: The Fathomless',
    'Warlock: The Fiend',
    'Warlock: The Genie',
    'Warlock: The Great Old One',
    'Warlock: The Hexblade',
    'Warlock: The Undying',
    'Warlock: The Undead',
    'Wizard',
    'Wizard: School of Abjuration',
    'Wizard: School of Conjuration',
    'Wizard: School of Divination',
    'Wizard: School of Enchantment',
    'Wizard: School of Evocation',
    'Wizard: School of Illusion',
    'Wizard: School of Necromancy',
    'Wizard: School of Transmutation',
    'Wizard: Bladesinging',
    'Wizard: Chronurgy Magic',
    'Wizard: Graviturgy Magic',
    'Wizard: Order of Scribes',
    'Wizard: War Magic'
] as const;

export type ClassTypes = typeof ALL_CLASS_TYPES[number];