import {AttributeType} from "../../02_models/023_Types/Attributes/AttributeTypes";
import {ClassTypes} from "../../02_models/023_Types/Character/ClassTypes";
import {ARTIFICER_TABLE} from "./ArtificerTable";
import {FULL_CASTER_TABLE} from "./FullCasterTable";
import {BLOOD_HUNTER_PROFANE_SOUL_TABLE} from "./BloodHunterProfaneSoulTable";
import {THIRD_CASTER_TABLE} from "./ThirdCasterTable";
import {HALF_CASTER_TABLE} from "./HalfCasterTable";
import {WARLOCK_TABLE} from "./WarlockTable";
import {MONK_TABLE} from "./MonkTable";

export const CLASS_SPELL_TABLE_CONNECTOR: Record<ClassTypes, any> = {
    'Artificer': ARTIFICER_TABLE,
    'Artificer: Alchemist': ARTIFICER_TABLE,
    'Artificer: Armorer': ARTIFICER_TABLE,
    'Artificer: Artillerist': ARTIFICER_TABLE,
    'Artificer: Battle Smith': ARTIFICER_TABLE,

    'Barbarian': null,
    'Barbarian: Path of the Ancestral Guardian': null,
    'Barbarian: Path of the Beast': null,
    'Barbarian: Path of the Berserker': null,
    'Barbarian: Path of the Giant': null,
    'Barbarian: Path of the Storm Herald': null,
    'Barbarian: Path of the Totem Warrior': null,
    'Barbarian: Path of Wild Magic': null,
    'Barbarian: Path of the Zealot': null,

    'Bard': FULL_CASTER_TABLE,
    'Bard: College of Creation': FULL_CASTER_TABLE,
    'Bard: College of Eloquence': FULL_CASTER_TABLE,
    'Bard: College of Glamour': FULL_CASTER_TABLE,
    'Bard: College of Lore': FULL_CASTER_TABLE,
    'Bard: College of Spirits': FULL_CASTER_TABLE,
    'Bard: College of Swords': FULL_CASTER_TABLE,
    'Bard: College of Valor': FULL_CASTER_TABLE,
    'Bard: College of Whispers': FULL_CASTER_TABLE,

    'Blood Hunter': null,
    'Blood Hunter: Order of the Ghostslayer': null,
    'Blood Hunter: Order of the Lycan': null,
    'Blood Hunter: Order of the Mutant': null,
    'Blood Hunter: Order of the Profane Soul': BLOOD_HUNTER_PROFANE_SOUL_TABLE,

    'Cleric': FULL_CASTER_TABLE,
    'Cleric: Arcana Domain': FULL_CASTER_TABLE,
    'Cleric: Death Domain': FULL_CASTER_TABLE,
    'Cleric: Forge Domain': FULL_CASTER_TABLE,
    'Cleric: Grave Domain': FULL_CASTER_TABLE,
    'Cleric: Knowledge Domain': FULL_CASTER_TABLE,
    'Cleric: Life Domain': FULL_CASTER_TABLE,
    'Cleric: Light Domain': FULL_CASTER_TABLE,
    'Cleric: Nature Domain': FULL_CASTER_TABLE,
    'Cleric: Order Domain': FULL_CASTER_TABLE,
    'Cleric: Peace Domain': FULL_CASTER_TABLE,
    'Cleric: Tempest Domain': FULL_CASTER_TABLE,
    'Cleric: Trickery Domain': FULL_CASTER_TABLE,
    'Cleric: Twilight Domain': FULL_CASTER_TABLE,
    'Cleric: War Domain': FULL_CASTER_TABLE,

    'Druid': FULL_CASTER_TABLE,
    'Druid: Circle of Dreams': FULL_CASTER_TABLE,
    'Druid: Circle of the Land': FULL_CASTER_TABLE,
    'Druid: Circle of the Moon': FULL_CASTER_TABLE,
    'Druid: Circle of the Shepherd': FULL_CASTER_TABLE,
    'Druid: Circle of Spores': FULL_CASTER_TABLE,
    'Druid: Circle of Stars': FULL_CASTER_TABLE,
    'Druid: Circle of Wildfire': FULL_CASTER_TABLE,

    'Fighter': null,
    'Fighter: Arcane Archer': null,
    'Fighter: Battle Master': null,
    'Fighter: Cavalier': null,
    'Fighter: Champion': null,
    'Fighter: Echo Knight': null,
    'Fighter: Eldritch Knight': THIRD_CASTER_TABLE,
    'Fighter: Psi Warrior': null,
    'Fighter: Rune Knight': null,
    'Fighter: Samurai': null,

    'Monk': MONK_TABLE,
    'Monk: Way of Mercy': MONK_TABLE,
    'Monk: Way of the Astral Self': MONK_TABLE,
    'Monk: Way of the Drunken Master': MONK_TABLE,
    'Monk: Way of the Four Elements': MONK_TABLE,
    'Monk: Way of the Kensei': MONK_TABLE,
    'Monk: Way of the Long Death': MONK_TABLE,
    'Monk: Way of the Open Hand': MONK_TABLE,
    'Monk: Way of the Shadow': MONK_TABLE,
    'Monk: Way of the Sun Soul': MONK_TABLE,
    'Monk: Way of the Ascendant Dragon': MONK_TABLE,

    'Paladin': HALF_CASTER_TABLE,
    'Paladin: Oath of Devotion': HALF_CASTER_TABLE,
    'Paladin: Oath of Glory': HALF_CASTER_TABLE,
    'Paladin: Oath of Redemption': HALF_CASTER_TABLE,
    'Paladin: Oath of Conquest': HALF_CASTER_TABLE,
    'Paladin: Oath of the Ancients': HALF_CASTER_TABLE,
    'Paladin: Oath of the Crown': HALF_CASTER_TABLE,
    'Paladin: Oath of the Watchers': HALF_CASTER_TABLE,
    'Paladin: Oathbreaker': HALF_CASTER_TABLE,
    'Paladin: Oath of Vengeance': HALF_CASTER_TABLE,

    'Ranger': HALF_CASTER_TABLE,
    'Ranger: Beast Master': HALF_CASTER_TABLE,
    'Ranger: Fey Wanderer': HALF_CASTER_TABLE,
    'Ranger: Gloom Stalker': HALF_CASTER_TABLE,
    'Ranger: Horizon Walker': HALF_CASTER_TABLE,
    'Ranger: Hunter': HALF_CASTER_TABLE,
    'Ranger: Monster Slayer': HALF_CASTER_TABLE,
    'Ranger: Swarmkeeper': HALF_CASTER_TABLE,
    'Ranger: Drakewarden': HALF_CASTER_TABLE,

    'Rogue': null,
    'Rogue: Arcane Trickster': THIRD_CASTER_TABLE,
    'Rogue: Assassin': null,
    'Rogue: Inquisitive': null,
    'Rogue: Mastermind': null,
    'Rogue: Phantom': null,
    'Rogue: Scout': null,
    'Rogue: Soulknife': null,
    'Rogue: Swashbuckler': null,
    'Rogue: Thief': null,

    'Sorcerer': FULL_CASTER_TABLE,
    'Sorcerer: Aberrant Mind': FULL_CASTER_TABLE,
    'Sorcerer: Clockwork Soul': FULL_CASTER_TABLE,
    'Sorcerer: Divine Soul': FULL_CASTER_TABLE,
    'Sorcerer: Draconic Bloodline': FULL_CASTER_TABLE,
    'Sorcerer: Shadow Magic': FULL_CASTER_TABLE,
    'Sorcerer: Storm Sorcery': FULL_CASTER_TABLE,
    'Sorcerer: Wild Magic': FULL_CASTER_TABLE,

    'Warlock': WARLOCK_TABLE,
    'Warlock: The Archfey': WARLOCK_TABLE,
    'Warlock: The Celestial': WARLOCK_TABLE,
    'Warlock: The Fathomless': WARLOCK_TABLE,
    'Warlock: The Fiend': WARLOCK_TABLE,
    'Warlock: The Genie': WARLOCK_TABLE,
    'Warlock: The Great Old One': WARLOCK_TABLE,
    'Warlock: The Hexblade': WARLOCK_TABLE,
    'Warlock: The Undying': WARLOCK_TABLE,
    'Warlock: The Undead': WARLOCK_TABLE,

    'Wizard': FULL_CASTER_TABLE,
    'Wizard: School of Abjuration': FULL_CASTER_TABLE,
    'Wizard: School of Conjuration': FULL_CASTER_TABLE,
    'Wizard: School of Divination': FULL_CASTER_TABLE,
    'Wizard: School of Enchantment': FULL_CASTER_TABLE,
    'Wizard: School of Evocation': FULL_CASTER_TABLE,
    'Wizard: School of Illusion': FULL_CASTER_TABLE,
    'Wizard: School of Necromancy': FULL_CASTER_TABLE,
    'Wizard: School of Transmutation': FULL_CASTER_TABLE,
    'Wizard: Bladesinging': FULL_CASTER_TABLE,
    'Wizard: Chronurgy Magic': FULL_CASTER_TABLE,
    'Wizard: Graviturgy Magic': FULL_CASTER_TABLE,
    'Wizard: Order of Scribes': FULL_CASTER_TABLE,
    'Wizard: War Magic': FULL_CASTER_TABLE
} as const;

export type ClassSpellTableConnectorType = keyof typeof CLASS_SPELL_TABLE_CONNECTOR;

export type AllClassSpellTableConnectorDict = Record<ClassSpellTableConnectorType, AttributeType>;