export type ArtisansToolType =
    'alchemists-supplies'
    | 'brewers-supplies'
    | 'calligraphers-supplies'
    | 'carpenters-tools'
    | 'cartographers-tools'
    | 'cobblers-tools'
    | 'cooks-utensils'
    | 'glassblowers-tools'
    | 'jewelers-kits'
    | 'leatherworkers-tools'
    | 'masons-tools'
    | 'painters-supplies'
    | 'potters-tools'
    | 'smiths-tools'
    | 'tinkers-tools'
    | 'weavers-tools'
    | 'woodcarvers-tools'
    | 'disguise-kit'
    | 'forgery-kit'
    | 'herbalism-kit'
    | 'navigators-tools'
    | 'poisoners-kit'
    | 'thieves-tools';
